Hotfix: continue with publish pipeline on error (#1306)

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -160,7 +160,7 @@ jobs:
     if: contains(github.ref, 'refs/tags/')
     timeout-minutes: 10
     runs-on: ubuntu-20.04
-    needs: [ run-tests ]
+    needs: [run-tests]
     env:
       REPORTS_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
       TWINE_USERNAME: __token__
@@ -179,12 +179,28 @@ jobs:
       - name: Build and publish packages
         # Hacky version for now :)
         run: |
+          FAILED=false
           cd soda
           for pack in *
           do
             pushd .
             cd $pack
+
+            echo "| Building $pack"
             python3 setup.py sdist bdist_wheel
-            twine upload dist/*
+
+            echo "| Uploading $pack to pypi"
+            UPLOAD_FAILED=false
+            twine upload dist/* || UPLOAD_FAILED=true
+            if [ $UPLOAD_FAILED = true ]; then
+              FAILED=true
+              echo "Failed to upload $pack"
+            fi
+
             popd
           done
+
+          if [ $FAILED = true ]; then
+            echo "There was an error, check the logs please."
+            exit 1
+          fi
